# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

# you can delete this line if you're not using Docker
image: archlinux/base

before_script:
  - pacman -Syyu --noconfirm && pacman -S ansible grep --noconfirm
   
build1:
  stage: build
  script:
    - mkdir tests/ansible-role.initialsetup
    - cp {tasks,defaults} tests/ansible-role.initialsetup -r
    - ansible-playbook tests/play.yaml
    - grep -i testuser1 /etc/passwd
    - grep -i testuser1 /etc/group
